#! /bin/bash

PYTHON_WIN="python"
PYTHON_UNIX="python3"

# Check if the OS is Windows, else UNIX
if [ "$OS" = "Windows_NT" ]; then
    PYHON_TO_USE=$PYTHON_WIN
else
    PYHON_TO_USE=$PYTHON_UNIX
fi

OPPONENT1="agent" # random | alphabeta | mcts | agent | human
OPPONENT2="agent"

# Run the program
$PYHON_TO_USE LINFO1361-Shobu/main.py -d -l logs/log.txt -w1 $OPPONENT1 -w2 $OPPONENT2

# replay : 
# $PYHON_TO_USE LINFO1361-Shobu/main.py -r logs/log.txt





# End of file