#! /bin/bash

PYTHON_WIN="python"
PYTHON_UNIX="python3"

# Check if the OS is Windows, else UNIX
if [ "$OS" = "Windows_NT" ]; then
    PYHON_TO_USE=$PYTHON_WIN
else
    PYHON_TO_USE=$PYTHON_UNIX
fi

OPPONENT_WHITE="random" # random | alphabeta | mcts | agent | human
OPPONENT_BLACK="random"

# Run the program
$PYHON_TO_USE LINFO1361-Shobu/main.py -d -l log.txt -w $OPPONENT_WHITE -b $OPPONENT_BLACK 

# replay : 
# $PYHON_TO_USE LINFO1361-Shobu/main.py -r logs/log.txt





# End of file